String? fullName;
String? eiDNumber;
String? nationality;
String? nationalityCode;
String? expiryDate;
String? dob;
String? gender;
String? photo;
String? docPhoto;
String selfiePhoto = "";
String? passportNumber;
String? issuingStateCode;
double photoMatchScore = 0;
bool? isEidChosen;
