name: investnation
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+166

environment:
  sdk: ">=2.19.4 <=3.3.8"

dependencies:
  app_links: ^3.4.5
  blur: ^3.1.0
  cached_memory_image: ^1.5.0
  cached_network_image: ^3.3.0
  clevertap_plugin: ^2.0.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.3
  dropdown_button2: ^2.3.7
  email_validator: ^2.1.17
  equatable: ^2.0.5
  event_bus: ^2.0.0
  external_app_launcher: ^3.1.0
  firebase_analytics: ^10.7.2
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.4.6
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_document_reader_api: ^6.9.2
  flutter_document_reader_core_fullrfid: ^6.9.0
  flutter_dotenv: ^5.0.2
  flutter_face_api: ^5.2.3
  flutter_face_core: ^5.2.0
  flutter_flavor: ^3.1.3
  flutter_image_compress: ^2.0.4
  flutter_inappwebview: 6.0.0-beta.32
  flutter_secure_storage: ^8.0.0
  flutter_sizer: ^1.0.5
  flutter_slidable: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_stories: ^0.3.1
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  flutter_widget_from_html: ^0.10.3
  fluttertoast: ^8.2.4
  fwfh_text_style: ^2.23.8
  http: ^1.1.0
  http_interceptor: ^2.0.0-beta.7
  http_proxy:
    git:
      url: https://github.com/wslaimin/http_proxy.git
      ref: pull/7/head
  iban: ^1.0.1
  image_cropper: ^5.0.0
  image_picker: ^1.0.1
  intl: ^0.18.1
  js_interop: ^0.0.1
  just_the_tooltip: ^0.0.12
  local_auth: ^2.1.6
  open_file: ^3.3.2
  package_info_plus: ^4.0.2
  path_provider: ^2.1.2
  pausable_timer: ^3.1.0+3
  percent_indicator: ^4.2.3
  pie_chart: ^5.4.0
  pinput: ^2.3.0
  platform_device_id: ^1.0.1
  pointycastle: ^3.7.3
  qr_flutter: ^4.1.0
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  story_view: ^0.15.0
  syncfusion_flutter_charts: ^23.1.43
  syncfusion_flutter_sliders: ^23.1.43
  url_launcher: ^6.1.14
  uuid: ^3.0.7
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_flavorizr: ^2.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  rename: ^2.1.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # remove_alpha_ios: true
  image_path: "assets/images/icons/launcher_icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icons/launcher_icon.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icons/launcher_icon.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icons/launcher_icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/icons/
    - assets/images/icons/splash_icon.svg
    - assets/images/banners/
    - assets/regula.license
    - .env
    - .env.production
    - .env.development
    - .env.sit
    - .env.uat

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay/SFPRODISPLAYREGULAR.OTF
          weight: 300
        - asset: assets/fonts/SFProDisplay/SFPRODISPLAYMEDIUM.OTF
          weight: 400
        - asset: assets/fonts/SFProDisplay/SFPRODISPLAYBOLD.OTF
          weight: 700
